### ISSUE TITLE
Error in decode data

### ISSUE THREAD

**Issue by mcuOne** [rudi48/dso150-110-plot#1]
Hey, if I get the data from the DSO then comes the following error message:
`Push DSO150 ADJ + V/DIV.
59
58
Traceback (most recent call last):
  File "dso150-110-plot.py", line 122, in <module>
    dsoHeader.append(sdat.decode("utf-8"))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe0 in position 2: invalid continuation byte`

**Comment by abhra0897** [comment]
> Hey, if I get the data from the DSO then comes the following error message:
> `Push DSO150 ADJ + V/DIV. 59 58 Traceback (most recent call last): File "dso150-110-plot.py", line 122, in <module> dsoHeader.append(sdat.decode("utf-8")) UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe0 in position 2: invalid continuation byte`

You can try [this software](https://github.com/abhra0897/DSO-150-Shell-PC-Plotter) that plots also in the frequency domain as well as in time domain.

**Comment by rudi48** [comment]
@mcuOne 
Sorry, I was on vacation, and missed your Email.

The error happens while reading the header data.
In order to debug that, please insert after line 120 the statement:
    print(ncount)
and run the program.
If the number is "0", it looks like an serial transmission error.
If ncount is ">0" try to print the data with (instead of the number):
    print(sdat)
and please tell me the data.

Regards, Rudolf

**Comment by csaboka21** [comment]
ncount is 1 one not working for me neither

**Comment by csaboka21** [comment]
In linux it's working in windows not. hm...

**Comment by csaboka21** [comment]
I made it :) in device manager-> serial adapter -> properites -> port options-> advanced -> uncheck fifo :)

**Comment by rudi48** [comment]
Congratulations csaboka21. Which Windows version do you have?

**Comment by csaboka21** [comment]
Windows 10, but it's not solved the problem completly.. it's only working from usb hub but not always but most of time from direct usb port it's still not working
